#!/usr/bin/env python3
import os
import subprocess


FOLDER_DIR = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.expanduser("~/.local/share/applications")
print(FOLDER_DIR)
print(APP_DIR)

print("Installing libs... this may take a bit {:")

subprocess.run([
    "bash",
    f"{FOLDER_DIR}/setup.sh"
], check=True)


os.makedirs(APP_DIR, exist_ok=True)
#
with open(f"{os.path.join(APP_DIR)}/NotesIDE.desktop", 'x') as f:
    CONTENT = f"""[Desktop Entry]
Name=NotesIDE
Exec=bash -c "{FOLDER_DIR}/run.sh"
Icon={FOLDER_DIR}/ico.png
Terminal=false
Type=Application
"""
    f.write(CONTENT)

os.chmod(os.path.join(APP_DIR, "NotesIDE.desktop"), 0o755)
os.chmod(os.path.join(FOLDER_DIR, "run.sh"), 0o755)
os.chmod(os.path.join(FOLDER_DIR, "setup.sh"), 0o755)
print("Close this window and check your app menu (be sure to pin us (; )")